package com.nova.luna.model

enum class ActionType {
    LAUNCH_APP,
    GO_HOME,
    GO_BACK,
    OPEN_RECENTS,
    OPEN_NOTIFICATIONS,
    CLICK_TEXT,
    SCROLL_FORWARD,
    SCROLL_BACKWARD,
    TYPE_TEXT,
    READ_NOTIFICATIONS,
    STOP_SERVICE,
    TAKE_SCREENSHOT,
    OPEN_SETTINGS,
    OPEN_ACCESSIBILITY_SETTINGS,
    OPEN_USAGE_ACCESS_SETTINGS,
    CALL_CONTACT,
    BLOCKED,
    UNKNOWN
}

