package com.nova.luna.model

enum class IntentType {
    OPEN_APP,
    NAVIGATION,
    INTERACTION,
    TEXT_ENTRY,
    READ_NOTIFICATIONS,
    CONTROL,
    SENSITIVE,
    CAB_BOOKING,
    FOOD_ORDER,
    GROCERY_BOOKING,
    COMMUNICATION,
    CONTENT_CREATION,
    MEDIA_CONTROL,
    SHOPPING,
    BLOCKED,
    UNKNOWN
}
