package com.nova.luna.agent

enum class AgentLoopStopReason {
    COMPLETED,
    NEEDS_USER_INPUT,
    NEEDS_CONFIRMATION,
    MANUAL_HANDOFF,
    BLOCKED_BY_SAFETY,
    MAX_STEPS_REACHED,
    MAX_RETRIES_REACHED,
    STUCK_DETECTED,
    NO_ACCESSIBILITY,
    WRONG_APP,
    LOGIN_REQUIRED,
    PAYMENT_REQUIRED,
    OTP_OR_SECRET_REQUIRED,
    CAPTCHA_REQUIRED,
    PERMISSION_REQUIRED,
    MODEL_UNAVAILABLE,
    UNKNOWN_FAILURE,
    USER_CANCELLED
}
