package com.nova.luna.screen

enum class ScreenType {
    HOME_SCREEN,
    SEARCH_SCREEN,
    RESULTS_SCREEN,
    SETTINGS_SCREEN,
    CAMERA_SCREEN,
    YOUTUBE_HOME,
    YOUTUBE_SEARCH,
    BROWSER_SEARCH,
    CAB_HOME,
    CAB_LOCATION_ENTRY,
    CAB_FARE_RESULTS,
    FOOD_HOME,
    FOOD_SEARCH,
    FOOD_RESTAURANT_RESULTS,
    GROCERY_HOME,
    GROCERY_SEARCH,
    MESSAGE_DRAFT,
    CALL_DIALER,
    PAYMENT_OR_CHECKOUT,
    LOGIN_OR_AUTH,
    OTP_SCREEN,
    CAPTCHA_SCREEN,
    PERMISSION_SCREEN,
    UNKNOWN
}
